name: Manual
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        default: info
        options:
          - info
          - warn
          - error
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{inputs.log-level}}"
